### ISSUE TITLE
Fix build script for Python 3 and Fix ASM built with `nasm`

### ISSUE THREAD

**Issue by LongnoseRob** [pvachon/tsl-sdr#2]
Hello I just tried to build tsl/sdr on mz desktop PC (archlinux on Intel Q6600) and got the following error  while trying to configure it before building it;
`[robby@robquad tsl-sdr]$ ./waf  configure
Traceback (most recent call last):
  File "/home/robby/builds/tsl-sdr/.waf3-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/robby/builds/tsl-sdr/.waf3-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/home/robby/builds/tsl-sdr/.waf3-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/home/robby/builds/tsl-sdr/.waf3-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/home/robby/builds/tsl-sdr/.waf3-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/robby/builds/tsl-sdr/.waf3-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/robby/builds/tsl-sdr/wscript", line 54, in options
    _loadTools(opt)
  File "/home/robby/builds/tsl-sdr/wscript", line 35, in _loadTools
    _checkSupportedArch(cpuArch)
  File "/home/robby/builds/tsl-sdr/wscript", line 30, in _checkSupportedArch
    raise Exception('Unsupported CPU architecture: {}'.format(cpuArchId))
Exception: Unsupported CPU architecture: b'x86_64'
`

**Comment by LongnoseRob** [comment]
Cpuld this be a python 2 vs. python 3 thing?
I have python 3.6.0 installed

**Comment by pvachon** [comment]
Indeed it is -- just fixed up the wscript, and tested with Python 3.5.3 in 31c574554f00cddb2968e26ecea9d0963530cd1c. Give it a shot!

**Comment by LongnoseRob** [comment]
That worked!

Thanks for the quick fix,
however still another error comes when building:

`../pager/pager_flex.c: In function ‘_pager_flex_phase_process’:
../pager/pager_flex.c:997:13: warning: variable ‘biw_m’ set but not used [-Wunused-but-set-variable]
             biw_m = 0;
             ^~~~~
../pager/pager_flex.c:996:13: warning: variable ‘biw_carry’ set but not used [-Wunused-but-set-variable]
             biw_carry = 0,
             ^~~~~~~~~
../pager/pager_flex.c:993:13: warning: variable ‘biw_prio’ set but not used [-Wunused-but-set-variable]
             biw_prio = 0,
             ^~~~~~~~
../pager/pager_flex.c:992:13: warning: variable ‘biw_cksum’ set but not used [-Wunused-but-set-variable]
     uint8_t biw_cksum = 0,
             ^~~~~~~~~

[33/72] Compiling tsl/coro/x86_64_coro_init.c
[34/72] Compiling tsl/coro/x86_64_coro_swap.S
../tsl/coro/x86_64_coro_swap.S:40: error: unknown 'cpu' type

Waf: Leaving directory `/home/robby/builds/tsl-sdr/build'
Build failed
 -> task in 'tsl' failed (exit status 1): 
	{task 140631517354752: asm x86_64_coro_swap.S -> x86_64_coro_swap.S.15.o}
['/usr/bin/nasm', '-f', 'elf64', '-I/home/robby/builds/tsl-sdr/build/', '-I/home/robby/builds/tsl-sdr/', '-DHAVE_RTLSDR=1', '-DHAVE_CONCURRENCYKIT=1', '-DHAVE_JANSSON=1', '-D_ATS_IN_TREE', '-D_GNU_SOURCE', '-DSYS_CACHE_LINE_LENGTH=64', '-DNDEBUG', '-DTSL_POINTER_SIZE=8', '-DCONFIG_DIRECTORY_DEFAULT="/etc/tsl"', '../tsl/coro/x86_64_coro_swap.S', '-o', 'tsl/coro/x86_64_coro_swap.S.15.o']`

**Comment by pvachon** [comment]
Ahh, this might be a quirk with `nasm` vs. `yasm`. I've commented out the relevant line in 61c37ad4c87b7d5bd003146aab04e2549a688b80 -- give it another shot. :-)

**Comment by pvachon** [comment]
Closing this -- I can't further reproduce the issue. Please reopen it if the problem still exists for you. :-)
